edition = "2021"
newline_style = "Unix"
use_field_init_shorthand = true
use_small_heuristics = "Default"
condense_wildcard_suffixes = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
hard_tabs = true
imports_layout = "Vertical"
imports_granularity = "Crate"
max_width = 120
binop_separator = "Back"
combine_control_expr = false
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_lit_single_line = false
trailing_semicolon = false
wrap_comments = true